Repository Chriscastanuela/fitlit-activity-tracker, pull requests merged in 2020-08, with the labels that each got.

#2 Add folders and files to project structure.
  test/activity-test.js
  test/hydration-test.js
  test/sleep-test.js
  test/users-test.js
Labels: enhancement

#3 User
  classes/User.js
  classes/user-repository.js
  package-lock.json
  test/users-test.js
  tests/User-Repository-Test.js
  tests/User-Test.js
  tests/activity-test.js
  tests/hydration-test.js
  tests/sleep-test.js
Labels: enhancement

#6 Feature/create user info card
  classes/User.js
  classes/user-repository.js
  src/index.html
  src/scripts.js
Labels: enhancement

#5 Hydration
  classes/Hydration-Repository.js
  classes/Hydration.js
  classes/user-repository.js
  tests/Hydration-Repository-Test.js
  tests/hydration-test.js
Labels: enhancement

#8 Feature/sleep classes
  classes/Sleep-All.js
  classes/Sleep-User.js
  classes/SleepRepository.js
  classes/UserSleep.js
  src/index.html
  tests/Sleep-User-Test.js
  tests/User-Test.js
  tests/hydration-test.js
  tests/sleep-repository-test.js
  tests/user-sleep-Test.js
Labels: incomplete

#9 Hydration
  classes/Hydration.js
  tests/hydration-test.js
Labels: Fix

#10 Feature/sleep classes
  classes/UserSleep.js
  tests/user-sleep-Test.js
Labels: enhancement

#12 Feature/sleep repo build
  classes/SleepRepository.js
  tests/sleep-repository-test.js
Labels: enhancement
